export const FETCH_INVOICES = 'FETCH_INVOICES';
export const FETCH_INVOICES_SUCCESSFUL = 'FETCH_INVOICES_SUCCESSFUL';

export const FETCH_CUSTOMERS = 'FETCH_CUSTOMERS';
export const FETCH_CUSTOMERS_SUCCESSFUL = 'FETCH_CUSTOMERS_SUCCESSFUL';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_SUCCESSFUL = 'FETCH_PRODUCTS_SUCCESSFUL';

export const CLEAR_INVOICE_DETAILS = 'CLEAR_INVOICE_DETAILS';
export const DELETE_INVOICE = 'DELETE_INVOICE';
export const DELETE_INVOICE_SUCCESSFUL = 'DELETE_INVOICE_SUCCESSFUL';
export const FETCH_INVOICE_DETAILS = 'FETCH_INVOICE_DETAILS';
export const FETCH_INVOICE_DETAILS_SUCCESSFUL = 'FETCH_INVOICE_DETAILS_SUCCESSFUL';
export const PUSH_INVOICE = 'PUSH_INVOICE';
export const PUSH_INVOICE_SUCCESSFUL = 'PUSH_INVOICE_SUCCESSFUL';
export const UPDATE_INVOICE_DETAILS = 'UPDATE_INVOICE_DETAILS';
export const SET_INVOICE_ACTIVE = 'SET_INVOICE_ACTIVE';

export const ADD_INVOICE_ITEM = 'ADD_INVOICE_ITEM';
export const ADD_INVOICE_ITEM_SUCCESSFUL = 'ADD_INVOICE_ITEM_SUCCESSFUL';
export const DELETE_INVOICE_ITEM = 'DELETE_INVOICE_ITEM';
export const DELETE_INVOICE_ITEM_SUCCESSFUL = 'DELETE_INVOICE_ITEM_SUCCESSFUL';
export const FETCH_INVOICE_ITEMS = 'FETCH_INVOICE_ITEMS';
export const FETCH_INVOICE_ITEMS_SUCCESSFUL = 'FETCH_INVOICE_ITEMS_SUCCESSFUL';
export const UPDATE_INVOICE_ITEMS_QUANTITY = 'UPDATE_INVOICE_ITEMS_QUANTITY';
export const UPDATE_INVOICE_ITEMS_QUANTITY_SUCCESSFUL = 'UPDATE_INVOICE_ITEMS_QUANTITY_SUCCESSFUL';
export const RECALCULATE_TOTAL = 'RECALCULATE_TOTAL';
export const CLEAR_INVOICE_DETAILS_FETCH_DATA = 'CLEAR_INVOICE_DETAILS_FETCH_DATA';

export const PUSH_PRODUCT = 'PUSH_PRODUCT';
export const PUSH_PRODUCT_SUCCESSFUL = 'PUSH_PRODUCT_SUCCESSFUL';
export const UPDATE_PRODUCT_DETAILS = 'UPDATE_PRODUCT_DETAILS';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const DELETE_PRODUCT_SUCCESSFUL = 'DELETE_PRODUCT_SUCCESSFUL';
export const SET_PRODUCT_ACTIVE = 'SET_PRODUCT_ACTIVE';
export const FETCH_PRODUCT_DETAILS = 'FETCH_PRODUCT_DETAILS';

